name: sphinx

channels:
  - conda-forge
dependencies:
  - python
  - sphinx<7
  - myst-parser
  - pydata-sphinx-theme
  - make
  - sphinx-togglebutton
  - pygments_anyscript
  - jinja2
  - ipython
  - linkify-it-py 
  - tomli
  - sphinx-copybutton
  - sphinxext-opengraph
  - sphinx-book-theme
  - sphinx-design
  - sphinxcontrib-youtube



